#!/bin/sh

repo_name=$1
test -z $repo_name && echo "Repo name required." 1>&2 && exit 1
user=`git config --global user.name`
curl -u $user https://api.github.com/user/repos -d "{\"name\":\"$repo_name\"}"
git init
git remote add origin "ssh://git@github.com/abelardogilm/$repo_name.git"

